/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#e1e2eb",
        "surface-dim": "#10131a",
        "outline": "#859399",
        "error": "#ffb4ab",
        "on-surface-variant": "#bbc9cf",
        "tertiary-fixed-dim": "#00e383",
        "on-primary-fixed": "#001f28",
        "tertiary-container": "#00dc7f",
        "on-tertiary": "#00391d",
        "primary": "#a4e6ff",
        "outline-variant": "#3c494e",
        "on-primary-fixed-variant": "#004e60",
        "background": "#10131a",
        "error-container": "#93000a",
        "inverse-on-surface": "#2e3037",
        "surface": "#10131a",
        "on-tertiary-fixed-variant": "#00522c",
        "surface-bright": "#363940",
        "surface-container-high": "#272a31",
        "inverse-primary": "#00677f",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#e9ddff",
        "on-error": "#690005",
        "surface-container": "#1d2026",
        "primary-container": "#00d1ff",
        "primary-fixed": "#b7eaff",
        "surface-variant": "#32353c",
        "on-secondary-fixed-variant": "#5700c9",
        "surface-container-low": "#191c22",
        "secondary": "#d1bcff",
        "on-tertiary-fixed": "#00210e",
        "surface-container-highest": "#32353c",
        "surface-container-lowest": "#0b0e14",
        "on-secondary-container": "#ddcdff",
        "secondary-container": "#7000ff",
        "surface-tint": "#4cd6ff",
        "tertiary": "#00fc92",
        "on-primary-container": "#00566a",
        "secondary-fixed-dim": "#d1bcff",
        "on-tertiary-container": "#005b31",
        "primary-fixed-dim": "#4cd6ff",
        "on-surface": "#e1e2eb",
        "on-secondary-fixed": "#23005b",
        "tertiary-fixed": "#5bffa1",
        "inverse-surface": "#e1e2eb",
        "on-secondary": "#3c0090",
        "on-primary": "#003543",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
