package com.medianet.service;

import com.medianet.dto.ComplianceFindingDto;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.w3c.dom.*;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.File;
import java.util.*;

/**
 * Idée 2 — OpenSCAP Compliance Service.
 *
 * Parses the XCCDF result XML file produced by OpenSCAP (oscap xccdf eval)
 * and returns a list of compliance rule results with pass/fail status.
 *
 * Expected file: {resultsDir}/openscap-results.xml
 * Generated by the scanner container using:
 * oscap xccdf eval --profile <PROFILE> --results openscap-results.xml \
 * --report openscap-report.html <XCCDF_GUIDE>
 */
@Service
public class ComplianceService {

    private static final Logger log = LoggerFactory.getLogger(ComplianceService.class);

    // XCCDF namespace used in OpenSCAP result files
    private static final String XCCDF_NS_12 = "http://checklists.nist.gov/xccdf/1.2";
    private static final String XCCDF_NS_11 = "http://checklists.nist.gov/xccdf/1.1";

    /**
     * Parse the OpenSCAP XCCDF result XML file and return a list of rule results.
     *
     * @param resultsDir path to the scan results directory
     * @param profile    the compliance profile name used (for labelling)
     * @return list of ComplianceFindingDto (one per evaluated rule)
     */
    public List<ComplianceFindingDto> parseComplianceResults(String resultsDir, String profile) {
        File xmlFile = new File(resultsDir, "openscap-results.xml");
        if (!xmlFile.exists() || xmlFile.length() == 0) {
            log.warn("[COMPLIANCE] openscap-results.xml not found in {}", resultsDir);
            return Collections.emptyList();
        }

        List<ComplianceFindingDto> findings = new ArrayList<>();
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            factory.setNamespaceAware(true);
            // Disable external entity processing (XXE prevention)
            factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
            factory.setFeature("http://xml.org/sax/features/external-general-entities", false);
            factory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);

            Document doc = factory.newDocumentBuilder().parse(xmlFile);
            doc.getDocumentElement().normalize();

            // Try XCCDF 1.2 namespace first, then 1.1
            NodeList ruleResults = doc.getElementsByTagNameNS(XCCDF_NS_12, "rule-result");
            if (ruleResults.getLength() == 0) {
                ruleResults = doc.getElementsByTagNameNS(XCCDF_NS_11, "rule-result");
            }
            if (ruleResults.getLength() == 0) {
                // Fallback: no namespace
                ruleResults = doc.getElementsByTagName("rule-result");
            }

            log.info("[COMPLIANCE] Parsing {} rule-result elements from OpenSCAP XML", ruleResults.getLength());

            for (int i = 0; i < ruleResults.getLength(); i++) {
                Element ruleResult = (Element) ruleResults.item(i);
                String ruleId = ruleResult.getAttribute("idref");
                String severity = ruleResult.getAttribute("severity");

                // Get result text (pass/fail/notapplicable/...)
                String result = getChildText(ruleResult, "result");

                // Find matching Rule definition for title and description
                String title = "";
                String description = "";
                Element ruleDefinition = findRuleDefinition(doc, ruleId);
                if (ruleDefinition != null) {
                    title = getChildText(ruleDefinition, "title");
                    description = getChildText(ruleDefinition, "description");
                    // Fallback severity from Rule definition if not on rule-result
                    if ((severity == null || severity.isBlank()) && ruleDefinition.hasAttribute("severity")) {
                        severity = ruleDefinition.getAttribute("severity");
                    }
                }

                // Skip rules that were not applicable or not checked — keep only
                // pass/fail/error
                if ("notapplicable".equalsIgnoreCase(result) || "notchecked".equalsIgnoreCase(result)) {
                    continue;
                }

                findings.add(ComplianceFindingDto.builder()
                        .ruleId(ruleId)
                        .title(title)
                        .result(result != null ? result.toLowerCase() : "unknown")
                        .severity(severity != null && !severity.isBlank() ? severity.toLowerCase() : "medium")
                        .description(description)
                        .profile(profile != null ? profile : "unknown")
                        .build());
            }

            log.info("[COMPLIANCE] Parsed {} findings ({} fail, {} pass)",
                    findings.size(),
                    findings.stream().filter(f -> "fail".equals(f.getResult())).count(),
                    findings.stream().filter(f -> "pass".equals(f.getResult())).count());

        } catch (Exception e) {
            log.error("[COMPLIANCE] Failed to parse openscap-results.xml: {}", e.getMessage());
        }

        return findings;
    }

    /**
     * Returns compliance summary statistics.
     */
    public Map<String, Object> buildSummary(List<ComplianceFindingDto> findings) {
        long pass = findings.stream().filter(f -> "pass".equals(f.getResult())).count();
        long fail = findings.stream().filter(f -> "fail".equals(f.getResult())).count();
        long total = pass + fail;
        double score = total == 0 ? 0.0 : Math.round((double) pass / total * 1000.0) / 10.0;

        long highFail = findings.stream()
                .filter(f -> "fail".equals(f.getResult()) && "high".equals(f.getSeverity())).count();
        long mediumFail = findings.stream()
                .filter(f -> "fail".equals(f.getResult()) && "medium".equals(f.getSeverity())).count();

        Map<String, Object> summary = new LinkedHashMap<>();
        summary.put("totalRules", total);
        summary.put("pass", pass);
        summary.put("fail", fail);
        summary.put("score", score);
        summary.put("highFail", highFail);
        summary.put("mediumFail", mediumFail);
        return summary;
    }

    // ── XML helpers ──────────────────────────────────────────────────────────

    private String getChildText(Element parent, String tagName) {
        // Try with XCCDF namespaces first
        for (String ns : new String[] { XCCDF_NS_12, XCCDF_NS_11, null }) {
            NodeList nodes = ns != null
                    ? parent.getElementsByTagNameNS(ns, tagName)
                    : parent.getElementsByTagName(tagName);
            if (nodes.getLength() > 0 && nodes.item(0).getTextContent() != null) {
                return nodes.item(0).getTextContent().trim();
            }
        }
        return "";
    }

    private Element findRuleDefinition(Document doc, String ruleId) {
        if (ruleId == null || ruleId.isBlank())
            return null;
        for (String ns : new String[] { XCCDF_NS_12, XCCDF_NS_11 }) {
            NodeList rules = doc.getElementsByTagNameNS(ns, "Rule");
            for (int i = 0; i < rules.getLength(); i++) {
                Element rule = (Element) rules.item(i);
                if (ruleId.equals(rule.getAttribute("id"))) {
                    return rule;
                }
            }
        }
        // Fallback no-namespace
        NodeList rules = doc.getElementsByTagName("Rule");
        for (int i = 0; i < rules.getLength(); i++) {
            Element rule = (Element) rules.item(i);
            if (ruleId.equals(rule.getAttribute("id"))) {
                return rule;
            }
        }
        return null;
    }
}
