package com.medianet.dto;

import java.time.LocalDateTime;
import java.util.List;

public record ServerNodeDetailDto(
        Long id,
        String name,
        String host,
        Integer port,
        String username,
        String nodeType,
        String authMethod,
        String environment,
        String templateKey,
        String owner,
        String clientName,
        String projectName,
        String runbookUrl,
        List<String> tags,
        String notes,
        String description,
        LocalDateTime lastScannedAt,
        String latestStatus,
        String hostname,
        String osName,
        String kernelVersion,
        String cpuSummary,
        String memorySummary,
        String diskSummary,
        String firewallStatus,
        String sshRootLogin,
        String dockerSummary,
        String certificateSummary,
        String summary,
        String journalExcerpt,
        Integer criticalCount,
        Integer warningCount,
        Integer infoCount,
        List<String> driftChanges,
        List<PortExposureDto> ports,
        List<ServiceStatusDto> services,
        List<HardeningFindingDto> findings,
        List<ConfigSnapshotDto> recentSnapshots) {
}